language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli@2.3.0
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "v2-messaging"
env:
  global:
  - ENCRYPTION_LABEL: 76c23508d8e4
  - COMMIT_AUTHOR_EMAIL: developerhelp@bandwidth.com
  - secure: lWCIGYkGWVADfhphwFFd5i3BxvBFn/+xfkWtB+hZD1MeqtWMPtarslrhJY5y3fjSi6dT+4ZQnpl8r1PLR6P3uAEZChXaBTik/jj/ELqLRnfL1xpfw7D8fEFqMlQ7nKvP+5oh8isHhJhMDucwRG4fY7KANZ+Tp5KNum32wlMRc0mgC88oATb34Xn1zPkCitbGlqRmrUz6mKSbKOaDVsl/ig8q0fx8anH//MdLQXy5490K8g9XOStglC8VQTZNvaPD/brQlSi+JOktB9eFzqi1CwP/aQAKRk0pXJFvEUB7QNdZLGkeFNw/MDe+g/j8qqAqYyZmZjjbeihHd3xL1Jhj/z+Mbkh/tQtIVZCvSfbDYpQ5ZTs/Xe448rhhcwRah/1pPNy27UczSSaxlo8R9cI9FXXn9DixuKGXRA8HcOAVL9zAnjJo1+lgA93f43kaZtJFoyetl0ml1GboNN+4OAM+0qo+7c3Gq0q78MthAuMRifmAtTrlLCGkAGy9L4RRIo7eBVg2QIyiCbCl/jb56ppaFviXpvO6l8nTqCYNspOWcB8uiDfWGm34zKQEZJnE97Aohn5W4V+C/gCUyDIKlF9ZvT0FKTIwWx5Y+Up0x2H/Su9FULKPAbTagK9ohsAY7R7Xe0N6VkufyuPGBCy/5/y6Iv5NSI0fdRFE8Ole1UEsDo8=
  - secure: JTrX8zlrxIi/+ImjnfoFFKWUpeY779Zvp58SlravxNx//bNhmU2yy4ZhKGOZOiTbi86okwX6dvV8TE8mm2MARr5a1bK6qUUbQj/6QHsXWpBagILjKwK3Q2i23GrYdZ3a8wgJWCbWC53Qupnm0UIoxTuoHCRNDDNdb872YmndKWZjLXWCPGKbs1UhOG8ZViFPIDrSht3Cyo6sx8Ys8Q4ihxvxpnEbE4pN+wi5JNwnznh59u4x0bh5RPpSx3YEeO59SKwKCHCcqYTxvbsG1i+l3v06p69jHNsiPJWdjyTGZv5koAyIm5G4oiHYSsvIni9NqFawmUDw1sPbubgGQszKRTEL75ucZbmT2369ysRCGb338WI/kqUIpGnrR2ujwp6RcS9h+UNBBm3AXdq4GIyWgwsz5J8cufIfGC4IXkWixG7rOnSM/NC65AxpA5+bTvMLrp4KRmfO/TtG0+w+uYI/6CNEh7NZwLwlAgN4I4DZwSJuYiH4wFqgNVW+c6hPpwkq+BlUuJoykIOIEpz2QmAJ1rI4AiMk920T9wuxSs3GUWnoxo9k9dLbxXB7UAQXMF6FYyR0TcwPnbPwdlFq78ih1yLsfh7dEY3gqVfG07ecWPzaCV86mr8FZb3YgFBdeiQR810TkT7lZoKlnv79Ggeub9y15Pqd++yXG5SAMzsLdO4=
  - secure: cIUxsxJiXrArCP0SSzUY7fdIkjXMVqdwnhV4dnQcRxoFdE1HQXxoBeprDj4SITVZax4NT2ip4Z1/Xc6xTF3BvsHn31CyVoxJD+eyU+egvJXeuSprewGuzsBZrT5LjEr7h2kkhiIs9UxoIAEBjAkUSJkPsrPjsCSydjxx/KcKzkCg384GmZ4g6Aj/U22hf6UhVHv9iZ8ZAJpe1e/LHyTUMPoscrrMllwMLNVYXzTZolKnRCPhiuyYQqQINzFIS5M4LyyozO/RZVZwBIrXmMiwi0lg7ZiQDhxvWlptHEVxRJJyeLHG899gJXVMXodFLum/1zW724DibWT46/t2ADcstcwXid2ixLoSNH5Ck4atSC/jr41FPjWcYciy2b9SmC/ms+xmy5KmAepG4s5N32ICdlEBDcyHLmWnMcnAo1stS2y4Ed+JwP0msD0Uwk1VsFMVprhybCrpeL7ot41jkhmkbbpn+WH1J/g+sf1OpmEtcXkkSiRPGwOSuyvvW9A/7aHLFFkmvmB5wxRhld/KQ6+hlBN+Ae/zISmEBlDYsLjr3/3TRizErM7IVQVeWCak3AYUZfO22LZ5X0b6gKFnfwAaRmiFTJNcei4UGt9q0T6sz3ykcOr15/AG5gJ4I+MB6NyCm6b/PFU+JIq27sXjy0JG8PuymP7P9JjUnv9wVmxc3fU=
