language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "v2-messaging"
env:
  global:
  - ENCRYPTION_LABEL: 76c23508d8e4
  - COMMIT_AUTHOR_EMAIL: dtolbert@bandwidth.com
  - secure: PgMmtbtVEzFMOmOhFi6z0o3XLvCalKSf/eJXAibLD/O5EWzLo/OvM0BYm/ErfQQUzFGXKaWwrWtKWFKv/vLfdMMgDeYEyXcdjB8egO3d3nuSsW3zoC8ynwNufzMv2Czyuo2C9bz+UqLd2BIZESkdKIeRYI3LBQ4gKqd7OS9wyTjBHnymgqM7vbDqv+Vks2ZwRP5LYPcSqog+0h+O9mFBgc69AnlOw3peObuQoULAw8YISSDiVoP3ctfETub8JoaZVdCMRCdybE4A8rSdzMc85IVsmxGW3/jujPfcRV+KXkIOX/mrpBaRk2/m2d5YyEHl41CCg2LqhaqOpUJQOIVGIzyytuS/vd92hMPRb6VExz6D9SMRurs1as8Dp01sCII6sFoiwoXcK0ulAVU10AjP4DGqjSGYFzpRF+1D053OzC+MXY5wvrmem/mYceMTwrp+eJbg2opbk6P3Tuy5CbXZ/oUr3Y0Q/PYVIjQIJ/HWeb4o1F2Jb+enBvCvtI4wYkZZXa11sbYllMFesfcZi1KMmxeSCMTPO+Cni2/Q/a+e04j5UezJikf+oQGGtWkMZZgUkIaAewjBjQ5BqviwFaJ6qEyCKcS/f+k2QY0ItzJIcmgYyZefEJb4wdDUs0Cn7AvDiAvREb1lMXt0hPWmrrobbIbImNjo+UjfMxl9m3tQ63I=
  - secure: FffKsBdBQKLi+wbsSUjHhEpHCKncMeQ9IbsBCIHg9HfFiEtWasTJU8kbriYTLCFMbV3hoMR9/A/33mRjzhA+X98AHmRFR5j+5Hkoci18WnU4PX2lX7wT9nrWMxp32uslbkpc1wpFYZsLnbnIxjVgDA83AiQ1qsLO5J6dxAF2KKsTJIc4VsghAixVeQIouni7Gfi14lnjyij8tiuIgfb33z3rG4lHiI1uF7lueY6zllKGT5fkGVEmc17TkvutczyQAd7lrOCvZCWt2RGs8YH/uPntj8y8lLMIKQi3gP+ETsJlUcM2JtNOjUFJ1jHyVUXlKXuYqExm1Pdqn5qiYbeBb401SGlUAcSzsZk4q/YDaCsajIHnrwvzeqH3orUQLV9OBm5zemBQJXizHxmXOmo8amBtfqyt4Q90EUSfduOmGkNz1I+bTAprmmiZOBeo/NNu+9kD43QFGiMEWStRyHDENO06M4q7T9lZ+122BULwFkdJjzX/97XNDGPsjFqG0YcYjr4ob32LbdGPFgIrJgRwaXct7zERrnbb4F4MZVppkH4XkW5lW6zqxxiDfNad5vCyX8fCS6MglRkqcV8q42DInRlA4IJuEDkasdV1nnX3eme0BJMknKQhzM475jLNphaCotEewReFHIc8CyM0tekSE+Xav4ijHAerUtr4UoTnEZQ=
  - secure: hHjdhLI1d66eiAQernNpBV6YpJZ7jBKvjPDgJarYM/MJNq1a9Do8aWbAy08PqJL74OH2NqtpNkwsLApAy4u5n2ggQRzVlLHM9Q7eQPyKMHbziuZ6ELISkuoUb37kWbs+3zfg2o37nnFl6kF0tbJmGXRlkNZicIyX+lDy9s7dedkam4p3AszGEXL54wQPyzSImNEYUNHlGxqinVvhuYcZDX6Rte8lzMw1i2kjqH+Z2q6Blep+WoBsU+VtGGAOXF3Z4DoMrMa06bPOxlq5pBZxKsyIeXs6OEw7Ew4EQxfbmb5ZbzlR/b4vSAdXH7SduVmYXiFm0I9XwfWTuPARMEGtyuSAllK81BvZm7mVBCIPpYjg0gPhXRmEmfiy/o6ZXRVmMeNPyauc0+syQ/L7LJ4JHb8hb1JEoXQ6BFZLglV7zZMg99J6bHt+utPqr0tftQrk56eWw4V0WRkb1vToQBsEKmLnALlMTmJ1fQo6eVChjLzoi28vehQQ3pUc371+6+OnTwebmYyOfFCEzIF5fM8ZVRl0JU04UOxuZDSF24pBvW+cyQl9KxaZPy1n7w8/Psdp1lbs63OXLuqJfyO7fQ9tjOA2F4xCXl44tt8s0BHlBSXEj3bzvsJisi9BAES7hjPV8wRQnzxIVY1+YR/viCcuNtanj4mVd3M1touqSpw+pRM=
